M48
; DRILL file {KiCad 9.0.1} date 2025-06-13T06:34:08+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-13T06:34:08+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X92.285Y-117.65
X92.285Y-123.43
T2
X90.678Y-58.293
X90.678Y-152.324
X171.069Y-152.324
X171.348Y-58.166
M30
