M48
; DRILL file {KiCad 9.0.1} date 2025-06-17T11:03:34+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-17T11:03:34+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X101.69Y-99.086
X101.69Y-104.866
T2
X99.06Y-38.66
X99.06Y-134.78
X181.46Y-38.662
X181.49Y-134.79
M30
